[versions]



[libraries]

paper = { group = "io.papermc.paper", name = "paper-api", version = "1.21.8-R0.1-SNAPSHOT" }
luckperms = { group = "net.luckperms", name = "api", version = "5.4" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version = "2.11.6" }
worldguardwrapper = { group = "org.codemc.worldguardwrapper", name = "worldguardwrapper", version = "1.2.0-SNAPSHOT" }

[plugins]

shadow = { id = "com.gradleup.shadow", version = "8.3.7" }
pluginyml-paper = { id = "net.minecrell.plugin-yml.paper", version = "0.6.0" }
